steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gcpdevops:latest'  # Replace [PROJECT_ID] and [IMAGE_NAME] with your values
      - '.'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gcpdevops:latest'  # Replace [PROJECT_ID] and [IMAGE_NAME] with your values
