steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gcpdevops'  # Replace [PROJECT_ID] and [IMAGE_NAME] with your values
      - '.'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gcpdevops'  # Replace [PROJECT_ID] and [IMAGE_NAME] with your values

  # Step 3: Deploying the Docker image to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'gcp-devops-project'
      - '--region'
      - 'us-central1-c'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'gke.yaml'
