apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/gcp-project-391816/gcpdevops:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name:  Port
            port:  5000

